cursor = '<CURSOR>'
port = 8123
proxy = "http://localhost:2023"

[[models]]
name = 'fitten_code'
type = 'fitten'
api = ''
model = ''
key = ''
username = 'xxxxxx'
password = 'xxxxxx'

[[models]]
name = 'longcat'
type = 'open_ai'
api = 'https://api.longcat.chat/openai/v1/chat/completions'
model = 'LongCat-Flash-Chat'
key = 'xxxxxx'
username = ''
password = ''

[[models]]
name = 'qwen'
type = 'open_ai'
api = 'https://api-inference.modelscope.cn/v1/chat/completions'
model = 'Qwen/Qwen3-Coder-480B-A35B-Instruct'
key = 'xxxxxx'
username = ''
password = ''

[[models]]
name = 'qwen2'
type = 'open_ai'
api = 'https://api-inference.modelscope.cn/v1/chat/completions'
model = 'Qwen/Qwen2.5-Coder-32B-Instruct'
key = 'xxxxxx'
username = ''
password = ''

[[models]]
name = 'qwen2.5'
type = 'open_ai'
api = 'https://api-inference.modelscope.cn/v1/chat/completions'
model = 'Qwen/Qwen2.5-72B-Instruct'
key = 'xxxxxx'
username = ''
password = ''

[[models]]
name = 'gemini'
type = 'open_ai'
api = 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions'
model = 'gemini-2.5-flash'
key = 'xxxxxx'
username = ''
password = ''
use_proxy=true

[[models]]
name = 'cfqwen'
type = 'cf'
api = 'https://api.cloudflare.com/client/v4/accounts/xxxx_account_id/ai/run/@cf/qwen/qwen2.5-coder-32b-instruct'
model = 'qwen2.5-coder-32b-instruct'
key = 'xxxxxx'
username = ''
password = ''

[[models]]
name = 'cfllama'
type = 'cf'
api = 'https://api.cloudflare.com/client/v4/accounts/xxxx_account_id/ai/run/@cf/meta/llama-3.3-70b-instruct-fp8-fast'
model = 'llama-3.3-70b-instruct-fp8-fast '
key = 'xxxxxx'
username = ''
password = ''

[[models]]
name = 'cfoss'
type = 'cf2'
api = 'https://api.cloudflare.com/client/v4/accounts/xxxx_account_id/ai/v1/responses'
model = '@cf/openai/gpt-oss-120b'
key = 'xxxxxx'
username = ''
password = ''
